@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Клиент" as Client
actor "Техник / Инкассатор" as Technician

rectangle "Банкомат (ATM)" {
    ' Основные варианты использования
    usecase "Снятие наличных" as Withdraw
    usecase "Запрос баланса" as CheckBalance
    usecase "Внесение наличных" as Deposit
    usecase "Перевод средств" as Transfer
    usecase "Смена ПИН-кода" as ChangePin
    
    ' Вспомогательные варианты
    usecase "Авторизация (Ввод PIN)" as Auth
    usecase "Печать чека" as PrintReceipt
    
    ' Служебные варианты
    usecase "Техническое обслуживание\nи инкассация" as Maintenance
}

actor "Служба авторизации\n(Банк)" as BankSystem
actor "Система мониторинга\nбезопасности" as SecuritySystem


' 1. Связи Клиента с функциями
Client -- Withdraw
Client -- CheckBalance
Client -- Deposit
Client -- Transfer
Client -- ChangePin

' 2. Связи между вариантами
' Чтобы снять деньги или проверить баланс, нужно пройти авторизацию
Withdraw ..> Auth
CheckBalance ..> Auth
Deposit ..> Auth
Transfer ..> Auth
ChangePin ..> Auth

' 3. Дополнительные опции
' Чек печатается по желанию
Withdraw <.. PrintReceipt
Deposit <.. PrintReceipt
Transfer <.. PrintReceipt
CheckBalance <.. PrintReceipt

' 4. Связи с внешними системами 
' Банкомат обращается к банку для проверки денег и счета
Withdraw -- BankSystem
CheckBalance -- BankSystem
Deposit -- BankSystem
Transfer -- BankSystem
ChangePin -- BankSystem

' 5. Связи Техника
Technician -- Maintenance
' Обслуживание фиксируется в системе безопасности
Maintenance -- SecuritySystem
@enduml